### ISSUE TITLE
feature request: comments in list files

### ISSUE THREAD

**Issue by msimerson** [haraka/haraka-plugin-access#17]
"(for example mail_from.access.whitelist or connect.rdns_access.whitelist) Do these files support comments (like "#" or ";") ? I would like to comment some IPs/Domainnames, why I added them, so I later can more easily maintain/remove them, if needed."

**Comment by baudehlo** [comment]
It's been forever, but IIRC 'list' files support # based comments.

**Comment by msimerson** [comment]
I quickly browsed through the plugin code (and haraka-config) looking for a line that would filter out  comments and didn't notice it. I'll test when I have a bit more time.

**Comment by baudehlo** [comment]
It's this:

https://github.com/haraka/haraka-config/blob/master/configfile.js#L11

And this:

https://github.com/haraka/haraka-config/blob/master/readers/flat.js#L19
