### ISSUE TITLE
Looking for a way to not send out mail to blocked domains. Would this help?

### ISSUE THREAD

**Issue by geertbrit** [haraka/haraka-plugin-access#22]
I'm evaluating Haraka as an outgoing mailserver to members. 
Some of these mails might bounce at the domain level. 

Could this plugin be used to: 

- automatically maintain a list of blocked domains
- make sure all email-addresses part of any of the blocked domains aren't send to again in the future?

**Comment by msimerson** [comment]
> automatically maintain a list of blocked domains

Among other things, this plugin *references* a list of blocked domains.

> make sure all email-addresses part of any of the blocked domains aren't send to again in the future?

That needs to be done at another level, like where the message is being generated.
