### ISSUE TITLE
Blocking outgoing mail to individual email-address not working with access plugin

### ISSUE THREAD

**Issue by geertbrit** [haraka/haraka-plugin-access#23]
### system info

Ubuntu 18.04
Haraka  2.8.2
Node v12.15.0

### Expected behavior

When adding <example@gmail.com> to config/access.domains I expect outgoing mail to be refused to this address. It this not possible through access-plugin? 

### Observed behavior

Outgoing mail is delivered to this address, in spite of the configuration. To add, adding a complete domain (e.g.: gmail.com) to config/access.domains then the email-address is correctly blocked 

### Steps to reproduce
- add access plugin to config/plugins
- add config/access.ini with contents `[check] any=true`
- add config/access.domains with contents `example@gmail.com`

**Comment by msimerson** [comment]
Do have a look at the **name** of the file, and then consider what its contents should be.

**Comment by rguleryuz** [comment]
Hello I' m having the same issue. Trying to create a blacklist for outgoing mail. Using haraka within poste.io.  

My access.ini file ;


[main]

[check]
any=false
conn=false
helo=false
mail=true
rcpt=true

[rcpt]
accept=false

[deny_msg]
conn=You are not allowed to connect
helo=That HELO is not allowed to connect
mail=That sender cannot send mail here
rcpt=That recipient is not allowed

My rcpt_to.access.blacklist file ;

somemail@gmail.com

screenshot of poste io connection. its seen on the connection screen that it hits as it show a red "access: rcpt_to.access.blacklist" but still sends the mail for some reason. Can you help ?

![image](https://user-images.githubusercontent.com/60223464/171191479-62f78686-3008-478f-9ce0-07a053dcb425.png)
