### ISSUE TITLE
Subdomains for internal email

### ISSUE THREAD

**Issue by kennylajara** [haraka/haraka-plugin-access#24]
I need to block outgoing emails from all the `@internal.example.com` to any non `@example.com` or `@sub.example.com` account (all my subdomains should be fine) while keeping the ability to send emails from `@example.com` or others subdomains to any address (including Gmail or Outlook that should be blocked for `@internal.example.com` accounts).

Can I do that with this plugin? How?

**Comment by msimerson** [comment]
duplicate of haraka/Haraka#2947
