### ISSUE TITLE
How to refresh cache in haraka

### ISSUE THREAD

**Issue by snipecoder** [haraka/haraka-plugin-access#31]
Hello

I found when updating for this example the file: access.domains
domain.com

I need to restart Haraka to take effect, any other way without interrupting the sending?
```
<** 550 Email from that domain is not accepted here.
 -> QUIT
```

Requires restarting Haraka to take effect.

**Comment by msimerson** [comment]
What OS?  Haraka's config file loader notices changes to config files and automatically reloads them. There are platform limitations.

**Comment by msimerson** [comment]
stale
